(() => {
const STORAGE_KEY="kompakt-lists-v1", DARK_KEY="maple-dark";
const DEFAULT={labels:{habits:"Hábitos",tasks:"Tareas",exercises:"Ejercicios"},tasks:[],habits:[],folders:[],lastPurge:0};
const DAYS=["L","M","M","J","V","S","D"];
let store=load(),tab="tasks",editing=false,openFolder=null,openHabit=null,dark=localStorage.getItem(DARK_KEY)==="1";
document.documentElement.classList.toggle("dark",dark);
const clone=x=>JSON.parse(JSON.stringify(x)), uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
const key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
function monday(d){let x=new Date(d);x.setHours(0,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x}
function addDays(d,n){let x=new Date(d);x.setDate(x.getDate()+n);return x}
function last2(now=new Date()){let d=new Date(now);d.setHours(2,0,0,0);if(d>now)d.setDate(d.getDate()-1);return d.getTime()}
function purge(s){let c=last2();return (s.lastPurge||0)>=c?s:{...s,lastPurge:c,tasks:(s.tasks||[]).filter(x=>!x.done)}}
function migrate(raw={}){
 let p={...clone(DEFAULT),...raw},legacy=raw?.lists;
 let tasks=p.tasks?.length?p.tasks:(legacy?.tasks||[]);
 let habits=(p.habits?.length?p.habits:(legacy?.habits||[]).map(i=>({id:i.id,name:i.text,marks:{}}))).map(h=>({...h,marks:h.marks||{}}));
 let folders=(p.folders||[]).map(f=>({...f,exercises:(f.exercises||[]).map(e=>({...e,done:Array.isArray(e.done)?e.done:[]}))}));
 return {labels:{...DEFAULT.labels,...(p.labels||{})},tasks,habits,folders,lastPurge:p.lastPurge||0};
}
function load(){try{return purge(migrate(JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}")))}catch{return clone(DEFAULT)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(store))}
function esc(s=""){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function move(a,f,t){if(t<0||t>=a.length)return a;let n=a.slice(),x=n.splice(f,1)[0];n.splice(t,0,x);return n}
function reorder(kind,i,dir,fid){if(kind==="tasks")store.tasks=move(store.tasks,i,i+dir);if(kind==="habits")store.habits=move(store.habits,i,i+dir);if(kind==="folders")store.folders=move(store.folders,i,i+dir);if(kind==="exercises"){let f=store.folders.find(x=>x.id===fid);if(f)f.exercises=move(f.exercises,i,i+dir)}save();render()}
function rc(k,i,l,f=""){return `<span class="reorder"><button data-r="${k}" data-i="${i}" data-d="-1" data-f="${f}" ${i===0?"disabled":""}>⌃</button><button data-r="${k}" data-i="${i}" data-d="1" data-f="${f}" ${i===l-1?"disabled":""}>⌄</button></span>`}
function editPanel(){return `<section class="edit-panel"><p class="eyebrow">Nombres de pestañas</p>${["habits","tasks","exercises"].map(k=>`<label class="rename-row"><span>${{habits:"↻",tasks:"✓",exercises:"⌁"}[k]}</span><input data-label="${k}" value="${esc(store.labels[k])}"></label>`).join("")}<div class="mode-row"><span>${dark?"☾":"☀"} Modo oscuro</span><button class="switch ${dark?"on":""}" id="dark"><span></span></button></div>${tab==="exercises"?'<div class="clear-row"><span>Desmarcar todos los sets</span><button id="clear">□</button></div>':""}</section>`}
function tasks(){return `<ul class="list">${store.tasks.map((x,i)=>`<li class="row task-row"><button class="check ${x.done?"on":""}" data-tt="${x.id}">${x.done?"✓":""}</button>${editing?`<input class="task-input ${x.done?"done":""}" data-tn="${x.id}" value="${esc(x.text)}">`:`<button class="task-text ${x.done?"done":""}" data-tt="${x.id}">${esc(x.text)}</button>`}${editing?rc("tasks",i,store.tasks.length):""}${editing?`<button class="delete" data-td="${x.id}">⌫</button>`:""}</li>`).join("")||'<li class="empty">Lista vacía.</li>'}</ul>`}
function habits(){
 let t=new Date();t.setHours(0,0,0,0);let m=monday(t),tk=key(t),ds=Array.from({length:7},(_,i)=>addDays(m,i));
 return `<ul class="list">${store.habits.map((h,i)=>`<li class="row"><div class="habit-head">${editing?`<input class="habit-name" data-hn="${h.id}" value="${esc(h.name)}">`:`<button class="habit-name" data-ho="${h.id}">${esc(h.name)}</button>`}${editing?rc("habits",i,store.habits.length):""}${editing?`<button class="delete" data-hd="${h.id}">⌫</button>`:""}</div><div class="week-grid">${ds.map((d,j)=>{let k=key(d),now=k===tk,on=!!h.marks[k];return `<div class="day ${now?"today":""}"><span class="day-label">${DAYS[j]}</span><button class="check ${on?"on":""}" ${now?`data-ht="${h.id}" data-date="${k}"`:"disabled"}>${on?"✓":""}</button></div>`}).join("")}</div></li>`).join("")||'<li class="empty">Sin hábitos.</li>'}</ul>`;
}
function year(h){let t=new Date(),y=t.getFullYear(),s=monday(new Date(y,0,1)),e=new Date(y,11,31),w=[];for(let d=new Date(s);d<=e;d=addDays(d,7))w.push(Array.from({length:7},(_,i)=>addDays(d,i)));let n=Object.values(h.marks).filter(Boolean).length;return `<div class="list"><p class="eyebrow">${y} · ${n} días marcados</p><div class="year-wrap"><div class="year-grid">${w.map(ww=>`<div class="week-col">${ww.map(d=>{let k=key(d),inside=d.getFullYear()===y,on=!!h.marks[k];return `<span class="dot ${!inside?"out":on?"on":""}" title="${k}"></span>`}).join("")}</div>`).join("")}</div></div></div>`}
function folders(){return `<ul class="list">${store.folders.map((f,i)=>`<li class="row folder-row"><span>□</span>${editing?`<input class="folder-name" data-fn="${f.id}" value="${esc(f.name)}">`:`<button class="folder-name" data-fo="${f.id}">${esc(f.name)}</button>`}<span class="count">${f.exercises.length}</span>${editing?rc("folders",i,store.folders.length):""}${editing?`<button class="delete" data-fd="${f.id}">⌫</button>`:""}</li>`).join("")||'<li class="empty">Sin carpetas. Agrega una abajo.</li>'}</ul>`}
function step(v,t,f,e){return `<div class="stepper"><button data-step="-1" data-type="${t}" data-f="${f}" data-e="${e}">−</button><span>${v}</span><button data-step="1" data-type="${t}" data-f="${f}" data-e="${e}">+</button></div>`}
function exercises(f){return `<div class="list"><div class="exercise-header"><span>Sets</span><span>Ejercicio</span><span>Reps</span><span>Kg</span></div>${f.exercises.map((e,i)=>`<div class="row"><div class="exercise-grid">${step(e.sets,"sets",f.id,e.id)}<input class="exercise-name" data-en="${e.id}" data-f="${f.id}" value="${esc(e.name)}">${step(e.reps,"reps",f.id,e.id)}${step(e.kg,"kg",f.id,e.id)}</div>${e.sets>0?`<div class="sets-row">${Array.from({length:e.sets},(_,si)=>`<button class="set-check ${e.done?.[si]?"on":""}" data-st="${si}" data-f="${f.id}" data-e="${e.id}">${e.done?.[si]?"✓":""}</button>`).join("")}</div>`:""}${editing?`<div class="exercise-actions">${rc("exercises",i,f.exercises.length,f.id)}<button class="delete" data-ed="${e.id}" data-f="${f.id}">⌫ Eliminar</button></div>`:""}</div>`).join("")||'<div class="empty">Sin ejercicios.</div>'}</div>`}
function addForm(inFL,inF){return `<form class="add-form" id="add"><input id="draft" placeholder="${inFL?"Nueva carpeta…":inF?"Nuevo ejercicio…":tab==="habits"?"Nuevo hábito…":"Agregar…"}"><button class="add" type="submit">${inFL?"□":"+"}</button></form>`}
function render(){
 let f=store.folders.find(x=>x.id===openFolder)||null,h=store.habits.find(x=>x.id===openHabit)||null,inF=tab==="exercises"&&f,inFL=tab==="exercises"&&!f,inH=tab==="habits"&&h,title=inF?f.name:inH?h.name:store.labels[tab];
 document.getElementById("app").innerHTML=`<div class="app"><nav class="tabs">${["habits","tasks","exercises"].map(k=>`<button class="tab ${tab===k?"active":""}" data-tab="${k}"><span class="ico">${{habits:"↻",tasks:"✓",exercises:"⌁"}[k]}</span><span>${esc(store.labels[k])}</span></button>`).join("")}</nav><button class="edit-btn ${editing?"active":""}" id="edit">${editing?"✕ Listo":"✎ Editar"}</button>${editing?editPanel():""}<div class="section-head">${inF||inH?'<button class="back" id="back">‹</button>':""}<h1 class="section-title">${esc(title)}</h1></div>${inH?year(h):tab==="habits"?habits():inFL?folders():inF?exercises(f):tasks()}${!inH?addForm(inFL,inF):""}<p class="footer">Las tareas completadas se borran a las 2:00 am</p></div>`;wire();
}
function wire(){
 document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;openFolder=openHabit=null;render()});document.getElementById("edit").onclick=()=>{editing=!editing;render()};document.getElementById("back")?.addEventListener("click",()=>{openFolder=openHabit=null;render()});
 document.getElementById("dark")?.addEventListener("click",()=>{dark=!dark;document.documentElement.classList.toggle("dark",dark);localStorage.setItem(DARK_KEY,dark?"1":"0");render()});
 document.getElementById("clear")?.addEventListener("click",()=>{store.folders=store.folders.map(f=>openFolder&&f.id!==openFolder?f:{...f,exercises:f.exercises.map(e=>({...e,done:[]}))});save();render()});
 document.querySelectorAll("[data-label]").forEach(i=>i.oninput=()=>{store.labels[i.dataset.label]=i.value;save()});
 document.querySelectorAll("[data-tt]").forEach(b=>b.onclick=()=>{let x=store.tasks.find(x=>x.id===b.dataset.tt);if(x)x.done=!x.done;save();render()});document.querySelectorAll("[data-tn]").forEach(i=>i.oninput=()=>{let x=store.tasks.find(x=>x.id===i.dataset.tn);if(x)x.text=i.value;save()});document.querySelectorAll("[data-td]").forEach(b=>b.onclick=()=>{store.tasks=store.tasks.filter(x=>x.id!==b.dataset.td);save();render()});
 document.querySelectorAll("[data-ho]").forEach(b=>b.onclick=()=>{openHabit=b.dataset.ho;render()});document.querySelectorAll("[data-hn]").forEach(i=>i.oninput=()=>{let h=store.habits.find(x=>x.id===i.dataset.hn);if(h)h.name=i.value;save()});document.querySelectorAll("[data-hd]").forEach(b=>b.onclick=()=>{store.habits=store.habits.filter(x=>x.id!==b.dataset.hd);save();render()});document.querySelectorAll("[data-ht]").forEach(b=>b.onclick=()=>{let h=store.habits.find(x=>x.id===b.dataset.ht);if(h)h.marks[b.dataset.date]=!h.marks[b.dataset.date];save();render()});
 document.querySelectorAll("[data-fo]").forEach(b=>b.onclick=()=>{openFolder=b.dataset.fo;render()});document.querySelectorAll("[data-fn]").forEach(i=>i.oninput=()=>{let f=store.folders.find(x=>x.id===i.dataset.fn);if(f)f.name=i.value;save()});document.querySelectorAll("[data-fd]").forEach(b=>b.onclick=()=>{store.folders=store.folders.filter(x=>x.id!==b.dataset.fd);save();render()});
 document.querySelectorAll("[data-en]").forEach(i=>i.oninput=()=>{let f=store.folders.find(x=>x.id===i.dataset.f),e=f?.exercises.find(x=>x.id===i.dataset.en);if(e)e.name=i.value;save()});document.querySelectorAll("[data-ed]").forEach(b=>b.onclick=()=>{let f=store.folders.find(x=>x.id===b.dataset.f);if(f)f.exercises=f.exercises.filter(x=>x.id!==b.dataset.ed);save();render()});
 document.querySelectorAll("[data-step]").forEach(b=>b.onclick=()=>{let f=store.folders.find(x=>x.id===b.dataset.f),e=f?.exercises.find(x=>x.id===b.dataset.e);if(!e)return;let t=b.dataset.type;e[t]=Math.max(0,Number(e[t])+Number(b.dataset.step));if(t==="sets"&&e.done?.length>e.sets)e.done=e.done.slice(0,e.sets);save();render()});
 document.querySelectorAll("[data-st]").forEach(b=>b.onclick=()=>{let f=store.folders.find(x=>x.id===b.dataset.f),e=f?.exercises.find(x=>x.id===b.dataset.e);if(!e)return;let si=Number(b.dataset.st),done=Array.from({length:Math.max(e.sets,si+1)},(_,i)=>!!e.done?.[i]);done[si]=!done[si];e.done=done;save();render()});
 document.querySelectorAll("[data-r]").forEach(b=>b.onclick=()=>reorder(b.dataset.r,Number(b.dataset.i),Number(b.dataset.d),b.dataset.f));
 document.getElementById("add")?.addEventListener("submit",ev=>{ev.preventDefault();let text=document.getElementById("draft").value.trim();if(!text)return;if(tab==="habits")store.habits.push({id:uid(),name:text,marks:{}});else if(tab==="exercises"&&!openFolder)store.folders.push({id:uid(),name:text,exercises:[]});else if(tab==="exercises"){store.folders.find(x=>x.id===openFolder)?.exercises.push({id:uid(),name:text,sets:4,reps:12,kg:10,done:[]})}else store.tasks.push({id:uid(),text,done:false});save();render()});
}
setInterval(()=>{let n=purge(store);if(n!==store){store=n;save();render()}},60000);
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));
render();
})();